/*
 * LogitechGenerator.cpp  —  AIR 树 → 罗技 Lua 代码生成器实现
 */
#include "LogitechGenerator.h"
#include "LogitechKeyMap.h"
#include <sstream>
#include <algorithm>
#include <cmath>
using namespace AIR;

LogitechGenerator::LogitechGenerator(std::vector<AIRDiagnostic>& diags)
    : m_diags(diags) {}

// ── 输出辅助 ──────────────────────────────────────────────────────────────────
std::string LogitechGenerator::ind() const { return std::string(m_depth*2,' '); } // Lua 惯用2空格
void LogitechGenerator::line(const std::string& s) { m_out << ind() << s << "\n"; }
void LogitechGenerator::write(const std::string& s) { m_out << s; }
void LogitechGenerator::nl()   { m_out << "\n"; }

std::string LogitechGenerator::expr(AIRNode& node) {
    LogitechGenerator sub(m_diags); node.accept(sub); return sub.result();
}
std::string LogitechGenerator::luaKey(AIRKey k, const std::string& raw) {
    if (k != AIRKey::KEY_UNKNOWN) { auto s=LogitechKeyMap::AIRKeyToLua(k); if(!s.empty()) return s; }
    return raw.empty() ? "unknown" : raw;
}
int LogitechGenerator::mouseBtn(AIRKey k) {
    int b = LogitechKeyMap::AIRKeyToLuaMouseBtn(k);
    return (b > 0) ? b : 1;
}
std::string LogitechGenerator::binOpStr(BinOp op) {
    switch(op){
    case BinOp::Add: return " + ";  case BinOp::Sub: return " - ";
    case BinOp::Mul: return " * ";  case BinOp::Div: return " / ";
    case BinOp::OpMod: return " % ";case BinOp::Pow: return " ^ "; // Lua 用 ^
    case BinOp::Eq:  return " == "; case BinOp::Neq: return " ~= "; // Lua 不等于是 ~=
    case BinOp::Lt:  return " < ";  case BinOp::Gt:  return " > ";
    case BinOp::Lte: return " <= "; case BinOp::Gte: return " >= ";
    case BinOp::OpAnd: return " and "; case BinOp::OpOr: return " or ";
    case BinOp::Concat: return " .. ";
    default: return " ? ";
    }
}
void LogitechGenerator::warn(const std::string& msg, int srcLine) {
    line("-- [WARNING] " + msg);
    m_diags.push_back({DiagLevel::Warning, srcLine, msg, "该节点已转为注释，请手动处理"});
}

// ── 程序结构 ──────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(ProgramNode& node) {
    line("-- Generated by LogitechPlugin v1.0.0");
    line("-- Logitech G HUB / LGS Lua Macro");
    nl();
    for (auto& c : node.children) { c->accept(*this); nl(); }
}

void LogitechGenerator::visit(SequenceNode& node) {
    for (auto& c : node.children) c->accept(*this);
}

void LogitechGenerator::visit(FunctionDefNode& node) {
    std::string sig = "function " + node.name + "(";
    for (size_t i=0;i<node.params.size();++i){ if(i) sig+=", "; sig+=node.params[i]; }
    sig += ")";
    line(sig); push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop(); line("end");
}

void LogitechGenerator::visit(FunctionCallNode& node) {
    std::string s = node.name + "(";
    for (size_t i=0;i<node.children.size();++i){ if(i) s+=", "; s+=expr(*node.children[i]); }
    line(s + ")");
}

// ── 触发器 / 热键 ─────────────────────────────────────────────────────────────
void LogitechGenerator::visit(TriggerNode& node) {
    // 转换为 OnEvent 函数
    std::string evStr, argStr;
    switch(node.triggerEvent) {
    case TriggerEvent::MouseButtonDown: evStr="MOUSE_BUTTON_PRESSED";  argStr=std::to_string(mouseBtn(node.key)); break;
    case TriggerEvent::MouseButtonUp:   evStr="MOUSE_BUTTON_RELEASED"; argStr=std::to_string(mouseBtn(node.key)); break;
    case TriggerEvent::KeyDown:         evStr="G_PRESSED";  argStr="1"; break;
    case TriggerEvent::KeyUp:           evStr="G_RELEASED"; argStr="1"; break;
    case TriggerEvent::MacroStart:      evStr="MACRO_START_EVENT"; argStr="1"; break;
    case TriggerEvent::MacroStop:       evStr="MACRO_STOP_EVENT";  argStr="1"; break;
    default: evStr="MOUSE_BUTTON_PRESSED"; argStr="1"; break;
    }

    line("function OnEvent(event, arg)");
    push();
    line("if event == \"" + evStr + "\" and arg == " + argStr + " then");
    push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop();
    line("end");
    pop();
    line("end");
}

void LogitechGenerator::visit(HotkeyNode& node) {
    // HotkeyNode → G_PRESSED/G_RELEASED（G 键宏按钮）
    // 如果是鼠标键，映射到 MOUSE_BUTTON_PRESSED
    std::string evStr, argStr;
    int mbtn = LogitechKeyMap::AIRKeyToLuaMouseBtn(node.key);
    if (mbtn > 0) {
        evStr = node.passthrough ? "MOUSE_BUTTON_PRESSED" : "MOUSE_BUTTON_PRESSED";
        argStr = std::to_string(mbtn);
    } else {
        evStr = "G_PRESSED"; argStr = "1";
    }
    line("function OnEvent(event, arg)");
    push();
    line("if event == \"" + evStr + "\" and arg == " + argStr + " then");
    push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop(); line("end");
    pop(); line("end");
}

// ── 控制流 ────────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(IfNode& node) {
    if (node.children.size()<2){warn("IfNode 不完整",node.srcLine);return;}
    write(ind()+"if "+expr(*node.children[0])+" then\n"); push();
    node.children[1]->accept(*this); pop();
    if (node.hasElse()) { line("else"); push(); node.children[2]->accept(*this); pop(); }
    line("end");
}

void LogitechGenerator::visit(LoopCountNode& node) {
    if (node.children.size()<2){warn("LoopCountNode 不完整");return;}
    write(ind()+"for _i = 1, "+expr(*node.children[0])+" do\n"); push();
    node.children[1]->accept(*this); pop(); line("end");
}

void LogitechGenerator::visit(LoopWhileNode& node) {
    if (node.children.size()<2){warn("LoopWhileNode 不完整");return;}
    write(ind()+"while "+expr(*node.children[0])+" do\n"); push();
    node.children[1]->accept(*this); pop(); line("end");
}

void LogitechGenerator::visit(LoopDoWhileNode& node) {
    // Lua 原生支持 repeat...until，语义完美对应
    if (node.children.size()<2){warn("LoopDoWhileNode 不完整");return;}
    line("repeat"); push();
    node.children[0]->accept(*this); pop();
    write(ind()+"until "+expr(*node.children[1])+"\n");
}

void LogitechGenerator::visit(LoopInfiniteNode& node) {
    line("while true do"); push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop(); line("end");
}

void LogitechGenerator::visit(BreakNode&)    { line("break"); }
void LogitechGenerator::visit(ContinueNode&) { warn("Lua 无 continue，已忽略"); }
void LogitechGenerator::visit(ReturnNode& node) {
    if (node.hasValue()) { write(ind()+"return "+expr(*node.children[0])+"\n"); }
    else line("return");
}
void LogitechGenerator::visit(LabelNode& node)  { warn("Lua 无标签，已忽略: "+node.name); }
void LogitechGenerator::visit(GotoNode& node)   { warn("Lua 无 goto，已忽略 → "+node.target); }

// ── 变量 ──────────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(VarAssignNode& node) {
    write(ind()+node.name+" = ");
    if (!node.children.empty()) write(expr(*node.children[0])); else write("nil");
    write("\n");
}
void LogitechGenerator::visit(VarDeclareNode& node) {
    std::string kw = (node.scope==VarScope::Local) ? "local " : "";
    if (node.hasInitValue()) { write(ind()+kw+node.name+" = "+expr(*node.children[0])+"\n"); }
    else line(kw+node.name+" = nil");
}

// ── 键盘动作 ──────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(KeyDownNode& node) {
    line("PressKey(\""+luaKey(node.key,node.rawKey)+"\")");
}
void LogitechGenerator::visit(KeyUpNode& node) {
    line("ReleaseKey(\""+luaKey(node.key,node.rawKey)+"\")");
}
void LogitechGenerator::visit(KeyTapNode& node) {
    std::string k = luaKey(node.key, node.rawKey);
    if (node.holdMs > 0) {
        // 需要按住一段时间
        line("PressKey(\""+k+"\")");
        line("Sleep("+std::to_string(node.holdMs)+")");
        line("ReleaseKey(\""+k+"\")");
    } else if (node.count > 1) {
        line("for _i=1,"+std::to_string(node.count)+" do");
        push(); line("PressAndReleaseKey(\""+k+"\")"); pop();
        line("end");
    } else {
        line("PressAndReleaseKey(\""+k+"\")");
    }
}
void LogitechGenerator::visit(KeySendStringNode& node) {
    // 罗技 Lua 无直接输入字符串的 API，逐字符发送
    line("-- SendText: \""+node.text+"\"  (逐键发送)");
    for (char c : node.text) {
        std::string ch(1,c);
        AIRKey k = LogitechKeyMap::LuaKeyToAIR(ch);
        std::string kn = (k!=AIRKey::KEY_UNKNOWN) ? LogitechKeyMap::AIRKeyToLua(k) : ch;
        line("PressAndReleaseKey(\""+kn+"\")");
    }
}

// ── 鼠标动作 ──────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(MouseMoveNode& node) {
    if (node.children.size()<2){warn("MouseMoveNode 缺坐标");return;}
    std::string x=expr(*node.children[0]), y=expr(*node.children[1]);
    if (node.coordType==CoordType::CoordRelative) line("MoveMouseRelative("+x+", "+y+")");
    else                                           line("MoveMouseTo("+x+", "+y+")");
}
void LogitechGenerator::visit(MouseClickNode& node) {
    int btn = mouseBtn(node.key);
    std::string bs = std::to_string(btn);
    for (int i=0;i<node.count;++i) {
        line("PressMouseButton("+bs+")");
        if (node.holdMs>0) line("Sleep("+std::to_string(node.holdMs)+")");
        line("ReleaseMouseButton("+bs+")");
    }
}
void LogitechGenerator::visit(MouseDownNode& node) {
    line("PressMouseButton("+std::to_string(mouseBtn(node.key))+")");
}
void LogitechGenerator::visit(MouseUpNode& node) {
    line("ReleaseMouseButton("+std::to_string(mouseBtn(node.key))+")");
}
void LogitechGenerator::visit(MouseScrollNode& node) {
    int clicks = 1;
    if (!node.children.empty()) {
        LogitechGenerator sub(m_diags); node.children[0]->accept(sub);
        try { clicks = std::stoi(sub.result()); } catch(...) {}
    }
    if (node.dir==ScrollDir::Down || node.dir==ScrollDir::Right) clicks = -clicks;
    line("MoveMouseWheel("+std::to_string(clicks)+")");
}

// ── 时间 ──────────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(SleepNode& node) {
    write(ind()+"Sleep(");
    if (!node.children.empty()) write(expr(*node.children[0])); else write("0");
    write(")\n");
}

// ── 查询 ──────────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(QueryKeyStateNode& node) {
    // 出现在表达式上下文，不加换行
    write("IsMouseButtonPressed("+std::to_string(mouseBtn(node.key))+")");
}

// ── 表达式 ────────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(ExprNumberNode& node) {
    if (node.value==(long long)node.value) write(std::to_string((long long)node.value));
    else write(std::to_string(node.value));
}
void LogitechGenerator::visit(ExprStringNode& node) {
    // Lua 字符串用双引号，\ 转义
    std::string esc;
    for (char c:node.value){if(c=='"')esc+="\\\"";else if(c=='\\')esc+="\\\\";else if(c=='\n')esc+="\\n";else esc+=c;}
    write("\""+esc+"\"");
}
void LogitechGenerator::visit(ExprBoolNode& node)  { write(node.value?"true":"false"); }
void LogitechGenerator::visit(ExprVarNode& node)   { write(node.name); }
void LogitechGenerator::visit(ExprCallNode& node) {
    write(node.name+"(");
    for(size_t i=0;i<node.children.size();++i){ if(i) write(", "); node.children[i]->accept(*this); }
    write(")");
}
void LogitechGenerator::visit(ExprBinopNode& node) {
    if(node.children.size()<2) return;
    write("("); node.children[0]->accept(*this);
    write(binOpStr(node.op));
    node.children[1]->accept(*this); write(")");
}
void LogitechGenerator::visit(ExprUnopNode& node) {
    if(node.children.empty()) return;
    write(node.op==UnOp::OpNot?"not (":"-( ");
    node.children[0]->accept(*this); write(")");
}
void LogitechGenerator::visit(ExprTernaryNode& node) {
    // Lua 无三元运算符，用 (cond and a or b) 模拟（有局限但常用）
    if(node.children.size()<3) return;
    write("("); node.children[0]->accept(*this); write(" and ");
    node.children[1]->accept(*this); write(" or ");
    node.children[2]->accept(*this); write(")");
}
void LogitechGenerator::visit(ExprRandomRangeNode& node) {
    // Lua → math.random(min, max)
    if(node.children.size()<2){write("math.random(0,100)");return;}
    write("math.random("); node.children[0]->accept(*this);
    write(", ");           node.children[1]->accept(*this); write(")");
}

// ── 元信息 ────────────────────────────────────────────────────────────────────
void LogitechGenerator::visit(CommentNode& node) {
    if (node.isInline) write("  -- "+node.text);
    else line("-- "+node.text);
}
void LogitechGenerator::visit(RawNode& node) { line("-- [RAW] "+node.code); }
