/*
 * RazerGenerator.cpp  —  AIR 树 → 雷蛇 XML 宏生成器实现
 */

#include "RazerGenerator.h"
#include "RazerKeyMap.h"
#include <sstream>
#include <algorithm>
#include <stdexcept>
#include <cstdio>    // sprintf

using namespace AIR;

// ============================================================================
//  构造 & 结果
// ============================================================================

RazerGenerator::RazerGenerator(std::vector<AIRDiagnostic>& diags)
    : m_diags(diags)
{
    m_macroName = "ConvertedMacro";
    m_macroGuid = "00000000-0000-0000-0000-000000000000";
}

std::string RazerGenerator::result() const
{
    return buildXml(m_macroName);
}

// ============================================================================
//  §1  辅助
// ============================================================================

void RazerGenerator::pushWarning(const std::string& msg, int line)
{
    FlatEvent ev;
    ev.kind = FlatEvent::Kind::Warning;
    ev.text = msg;
    pushEvent(ev);
    m_diags.push_back({ DiagLevel::Warning, line, msg,
                        "该节点在雷蛇格式中无对应表达，已转为注释" });
}

// 从表达式节点提取整数值（支持 ExprNumberNode 和 ExprRandomRangeNode 取中值）
int RazerGenerator::evalIntExpr(AIRNode* node, int defaultVal)
{
    if (!node) return defaultVal;
    if (auto* n = dynamic_cast<ExprNumberNode*>(node))
        return (int)n->value;
    if (auto* n = dynamic_cast<ExprRandomRangeNode*>(node)) {
        // 随机范围取中间值（近似）
        int lo = n->children.size() > 0
                 ? evalIntExpr(n->children[0].get(), 0) : 0;
        int hi = n->children.size() > 1
                 ? evalIntExpr(n->children[1].get(), 0) : 0;
        return (lo + hi) / 2;
    }
    return defaultVal;
}

std::string RazerGenerator::xmlEscape(const std::string& s)
{
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        switch (c) {
        case '&': out += "&amp;";  break;
        case '<': out += "&lt;";   break;
        case '>': out += "&gt;";   break;
        case '"': out += "&quot;"; break;
        case '\'':out += "&apos;"; break;
        default:  out += c;        break;
        }
    }
    return out;
}

// ============================================================================
//  §2  XML 构建
// ============================================================================

std::string RazerGenerator::buildXml(const std::string& macroName) const
{
    std::ostringstream xml;
    xml << "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
    xml << "<!-- Generated by RazerPlugin v1.0.0 -->\n";
    xml << "<Macro "
           "xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
           "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n";
    xml << "  <Name>" << xmlEscape(macroName) << "</Name>\n";
    xml << "  <Guid>" << m_macroGuid << "</Guid>\n";
    xml << "  <MacroEvents>\n";

    size_t i = 0;
    while (i < m_events.size()) {
        const FlatEvent& ev = m_events[i];

        switch (ev.kind) {

        case FlatEvent::Kind::Comment:
            xml << "    <!-- " << xmlEscape(ev.text) << " -->\n";
            ++i;
            break;

        case FlatEvent::Kind::Warning:
            xml << "    <!-- [WARNING] " << xmlEscape(ev.text) << " -->\n";
            ++i;
            break;

        case FlatEvent::Kind::Sleep:
            xml << "    <MacroEvent>\n";
            xml << "      <Type>6</Type>\n";
            xml << "      <Delay>" << ev.delay << "</Delay>\n";
            xml << "    </MacroEvent>\n";
            ++i;
            break;

        case FlatEvent::Kind::KeyDown:
            xml << "    <MacroEvent>\n";
            xml << "      <Type>1</Type>\n";
            xml << "      <Delay>" << ev.delay << "</Delay>\n";
            xml << "      <KeyboardEvent>\n";
            {
                std::string kn = ev.key != AIRKey::KEY_UNKNOWN
                    ? RazerKeyMap::AIRKeyToRazer(ev.key)
                    : ev.rawKey;
                xml << "        <Key>" << xmlEscape(kn) << "</Key>\n";
            }
            xml << "      </KeyboardEvent>\n";
            xml << "    </MacroEvent>\n";
            ++i;
            break;

        case FlatEvent::Kind::KeyUp:
            xml << "    <MacroEvent>\n";
            xml << "      <Type>2</Type>\n";
            xml << "      <Delay>" << ev.delay << "</Delay>\n";
            xml << "      <KeyboardEvent>\n";
            {
                std::string kn = ev.key != AIRKey::KEY_UNKNOWN
                    ? RazerKeyMap::AIRKeyToRazer(ev.key)
                    : ev.rawKey;
                xml << "        <Key>" << xmlEscape(kn) << "</Key>\n";
            }
            xml << "      </KeyboardEvent>\n";
            xml << "    </MacroEvent>\n";
            ++i;
            break;

        case FlatEvent::Kind::MouseDown:
            xml << "    <MacroEvent>\n";
            xml << "      <Type>4</Type>\n";
            xml << "      <Delay>" << ev.delay << "</Delay>\n";
            xml << "      <MouseButtonEvent>\n";
            xml << "        <Button>"
                << RazerKeyMap::AIRKeyToRazerMouseButton(ev.key)
                << "</Button>\n";
            xml << "      </MouseButtonEvent>\n";
            xml << "    </MacroEvent>\n";
            ++i;
            break;

        case FlatEvent::Kind::MouseUp:
            xml << "    <MacroEvent>\n";
            xml << "      <Type>5</Type>\n";
            xml << "      <Delay>" << ev.delay << "</Delay>\n";
            xml << "      <MouseButtonEvent>\n";
            xml << "        <Button>"
                << RazerKeyMap::AIRKeyToRazerMouseButton(ev.key)
                << "</Button>\n";
            xml << "      </MouseButtonEvent>\n";
            xml << "    </MacroEvent>\n";
            ++i;
            break;

        case FlatEvent::Kind::MouseMove:
            // 连续 MouseMove 事件合并为同一个 Type=3 的 MacroEvent
            xml << "    <MacroEvent>\n";
            xml << "      <Type>3</Type>\n";
            xml << "      <Delay>" << ev.delay << "</Delay>\n";
            xml << "      <MouseMovement>\n";
            while (i < m_events.size() &&
                   m_events[i].kind == FlatEvent::Kind::MouseMove) {
                const FlatEvent& mv = m_events[i];
                xml << "        <MouseMovementEvent>\n";
                xml << "          <Type>3</Type>\n";
                xml << "          <X>" << mv.x << "</X>\n";
                xml << "          <Y>" << mv.y << "</Y>\n";
                if (mv.delay > 0)
                    xml << "          <Delay>" << mv.delay << "</Delay>\n";
                xml << "        </MouseMovementEvent>\n";
                ++i;
            }
            xml << "      </MouseMovement>\n";
            xml << "    </MacroEvent>\n";
            break;
        }
    }

    xml << "  </MacroEvents>\n";
    xml << "  <IsFolder>false</IsFolder>\n";
    xml << "  <FolderGuid>00000000-0000-0000-0000-000000000000</FolderGuid>\n";
    xml << "</Macro>\n";

    return xml.str();
}

// ============================================================================
//  §3  IAIRVisitor 实现
// ============================================================================

// ── 程序结构 ──────────────────────────────────────────────────────────────────

void RazerGenerator::visit(ProgramNode& node)
{
    // 提取宏名称（来自顶层 CommentNode 或默认）
    for (auto& child : node.children) {
        if (child->type == AIRNodeType::Comment) {
            auto* c = static_cast<CommentNode*>(child.get());
            // 若注释含 "雷蛇宏:" 前缀，提取宏名
            const std::string prefix = "雷蛇宏: ";
            size_t p = c->text.find(prefix);
            if (p != std::string::npos) {
                size_t end = c->text.find("  (", p);
                m_macroName = c->text.substr(
                    p + prefix.size(),
                    end == std::string::npos
                        ? std::string::npos
                        : end - p - prefix.size());
            }
        }
        child->accept(*this);
    }
}

void RazerGenerator::visit(SequenceNode& node)
{
    for (auto& child : node.children)
        child->accept(*this);
}

void RazerGenerator::visit(HotkeyNode& node)
{
    // 热键体直接展开（雷蛇格式不含触发器定义，触发由硬件决定）
    FlatEvent ev;
    ev.kind = FlatEvent::Kind::Comment;
    ev.text = "热键触发器（雷蛇格式不含触发器，由鼠标硬件决定触发键）";
    pushEvent(ev);

    for (auto& child : node.children)
        child->accept(*this);
}

void RazerGenerator::visit(TriggerNode& node)
{
    FlatEvent ev;
    ev.kind = FlatEvent::Kind::Comment;
    ev.text = "事件触发器（雷蛇格式不含触发器定义）";
    pushEvent(ev);

    for (auto& child : node.children)
        child->accept(*this);
}

void RazerGenerator::visit(FunctionDefNode& node)
{
    pushWarning("函数定义（" + node.name + "）在雷蛇格式中不支持，内容已展开");
    // 尽量展开函数体
    if (!node.children.empty())
        node.children[0]->accept(*this);
}

void RazerGenerator::visit(FunctionCallNode& node)
{
    pushWarning("函数调用（" + node.name + "）在雷蛇格式中不支持");
}

// ── 控制流（雷蛇宏是线性序列，不支持分支/循环，尽量展开）────────────────────

void RazerGenerator::visit(IfNode& node)
{
    pushWarning("if 分支在雷蛇格式中不支持（仅展开 then 分支）");
    if (node.children.size() >= 2)
        node.children[1]->accept(*this); // 展开 then 分支
}

void RazerGenerator::visit(LoopCountNode& node)
{
    // 尝试展开固定次数循环
    int count = 1;
    if (!node.children.empty())
        count = evalIntExpr(node.children[0].get(), 1);

    if (count > 100) {
        pushWarning("循环次数 " + std::to_string(count) +
                    " 过多，已限制为 100 次（雷蛇宏不支持循环，需展开）");
        count = 100;
    } else {
        FlatEvent ev;
        ev.kind = FlatEvent::Kind::Comment;
        ev.text = "Loop " + std::to_string(count) + "次（展开）";
        pushEvent(ev);
    }

    if (node.children.size() >= 2) {
        for (int i = 0; i < count; ++i)
            node.children[1]->accept(*this);
    }
}

void RazerGenerator::visit(LoopWhileNode& node)
{
    pushWarning("while 循环在雷蛇格式中不支持，已跳过");
}

void RazerGenerator::visit(LoopDoWhileNode& node)
{
    pushWarning("do-while 循环在雷蛇格式中不支持，已跳过");
}

void RazerGenerator::visit(LoopInfiniteNode& node)
{
    pushWarning("无限循环在雷蛇格式中不支持，已跳过");
}

void RazerGenerator::visit(BreakNode&)    { pushWarning("break 在雷蛇格式中无效"); }
void RazerGenerator::visit(ContinueNode&) { pushWarning("continue 在雷蛇格式中无效"); }
void RazerGenerator::visit(ReturnNode&)   { pushWarning("return 在雷蛇格式中无效"); }
void RazerGenerator::visit(LabelNode& n)  { pushWarning("标签 " + n.name + " 在雷蛇格式中无效"); }
void RazerGenerator::visit(GotoNode& n)   { pushWarning("goto " + n.target + " 在雷蛇格式中无效"); }

// ── 变量 ──────────────────────────────────────────────────────────────────────

void RazerGenerator::visit(VarAssignNode& n)
{
    pushWarning("变量赋值（" + n.name + "）在雷蛇格式中不支持");
}

void RazerGenerator::visit(VarDeclareNode& n)
{
    pushWarning("变量声明（" + n.name + "）在雷蛇格式中不支持");
}

// ── 键盘动作 ──────────────────────────────────────────────────────────────────

void RazerGenerator::visit(KeyDownNode& node)
{
    FlatEvent ev;
    ev.kind   = FlatEvent::Kind::KeyDown;
    ev.delay  = 0;
    ev.key    = node.key;
    ev.rawKey = node.rawKey;
    pushEvent(ev);
}

void RazerGenerator::visit(KeyUpNode& node)
{
    FlatEvent ev;
    ev.kind   = FlatEvent::Kind::KeyUp;
    ev.delay  = 0;
    ev.key    = node.key;
    ev.rawKey = node.rawKey;
    pushEvent(ev);
}

void RazerGenerator::visit(KeyTapNode& node)
{
    // 展开为 KeyDown + [holdMs Sleep] + KeyUp，重复 count 次
    for (int i = 0; i < node.count; ++i) {
        FlatEvent down;
        down.kind   = FlatEvent::Kind::KeyDown;
        down.delay  = 0;
        down.key    = node.key;
        down.rawKey = node.rawKey;
        pushEvent(down);

        if (node.holdMs > 0) {
            FlatEvent sl;
            sl.kind  = FlatEvent::Kind::Sleep;
            sl.delay = node.holdMs;
            pushEvent(sl);
        }

        FlatEvent up;
        up.kind   = FlatEvent::Kind::KeyUp;
        up.delay  = 0;
        up.key    = node.key;
        up.rawKey = node.rawKey;
        pushEvent(up);
    }
}

void RazerGenerator::visit(KeySendStringNode& node)
{
    // 将文本拆解为逐字符的 KeyDown + KeyUp 序列
    // 注意：特殊字符（如大写字母）需要 Shift，这里简化处理只发基础键
    FlatEvent cmt;
    cmt.kind = FlatEvent::Kind::Comment;
    cmt.text = "SendText: " + node.text + "（字符逐键发送，大小写可能有损）";
    pushEvent(cmt);

    for (char c : node.text) {
        std::string ch(1, c);
        AIRKey key = RazerKeyMap::RazerKeyToAIR(ch);

        // 大写字母 → Shift + 小写
        bool needShift = (c >= 'A' && c <= 'Z');
        if (needShift) {
            FlatEvent shDown;
            shDown.kind = FlatEvent::Kind::KeyDown;
            shDown.key  = AIRKey::KEY_LSHIFT;
            pushEvent(shDown);
            // 转为小写查键
            std::string lc(1, (char)std::tolower((unsigned char)c));
            key = RazerKeyMap::RazerKeyToAIR(lc);
        }

        FlatEvent down;
        down.kind   = FlatEvent::Kind::KeyDown;
        down.key    = key;
        down.rawKey = ch;
        pushEvent(down);

        FlatEvent up;
        up.kind   = FlatEvent::Kind::KeyUp;
        up.key    = key;
        up.rawKey = ch;
        pushEvent(up);

        if (needShift) {
            FlatEvent shUp;
            shUp.kind = FlatEvent::Kind::KeyUp;
            shUp.key  = AIRKey::KEY_LSHIFT;
            pushEvent(shUp);
        }
    }
}

// ── 鼠标动作 ──────────────────────────────────────────────────────────────────

void RazerGenerator::visit(MouseMoveNode& node)
{
    if (node.children.size() < 2) {
        pushWarning("MouseMoveNode 缺少坐标子节点");
        return;
    }

    int x = evalIntExpr(node.children[0].get(), 0);
    int y = evalIntExpr(node.children[1].get(), 0);

    if (node.coordType == CoordType::CoordRelative) {
        // 雷蛇格式不支持相对坐标，发出警告并以相对值作为绝对值输出
        m_diags.push_back({
            DiagLevel::Warning, node.srcLine,
            "雷蛇格式只支持绝对坐标（Type=3）。"
            "相对移动 (" + std::to_string(x) + ", " + std::to_string(y) +
            ") 已按绝对坐标输出，请手动校正。",
            "将来源宏的相对坐标转为绝对坐标后再生成"
        });
    }

    FlatEvent ev;
    ev.kind  = FlatEvent::Kind::MouseMove;
    ev.delay = 0;
    ev.x     = x;
    ev.y     = y;
    pushEvent(ev);
}

void RazerGenerator::visit(MouseClickNode& node)
{
    // 展开为 MouseDown + [holdMs Sleep] + MouseUp，重复 count 次
    for (int i = 0; i < node.count; ++i) {
        FlatEvent down;
        down.kind  = FlatEvent::Kind::MouseDown;
        down.delay = 0;
        down.key   = node.key;
        pushEvent(down);

        if (node.holdMs > 0) {
            FlatEvent sl;
            sl.kind  = FlatEvent::Kind::Sleep;
            sl.delay = node.holdMs;
            pushEvent(sl);
        }

        FlatEvent up;
        up.kind  = FlatEvent::Kind::MouseUp;
        up.delay = 0;
        up.key   = node.key;
        pushEvent(up);
    }
}

void RazerGenerator::visit(MouseDownNode& node)
{
    FlatEvent ev;
    ev.kind  = FlatEvent::Kind::MouseDown;
    ev.delay = 0;
    ev.key   = node.key;
    pushEvent(ev);
}

void RazerGenerator::visit(MouseUpNode& node)
{
    FlatEvent ev;
    ev.kind  = FlatEvent::Kind::MouseUp;
    ev.delay = 0;
    ev.key   = node.key;
    pushEvent(ev);
}

void RazerGenerator::visit(MouseScrollNode& node)
{
    pushWarning("滚轮事件在雷蛇 XML 宏中不支持（Synapse 无对应 MacroEvent 类型）");
}

// ── 时间 ──────────────────────────────────────────────────────────────────────

void RazerGenerator::visit(SleepNode& node)
{
    int ms = 0;
    if (!node.children.empty())
        ms = evalIntExpr(node.children[0].get(), 0);

    FlatEvent ev;
    ev.kind  = FlatEvent::Kind::Sleep;
    ev.delay = ms;
    pushEvent(ev);
}

// ── 查询 & 表达式（不产生 MacroEvent，推警告）────────────────────────────────

void RazerGenerator::visit(QueryKeyStateNode& n)
{
    pushWarning("GetKeyState 在雷蛇格式中不支持");
}
void RazerGenerator::visit(ExprNumberNode&)   {}  // 由父节点 evalIntExpr 处理
void RazerGenerator::visit(ExprStringNode&)   {}
void RazerGenerator::visit(ExprBoolNode&)     {}
void RazerGenerator::visit(ExprVarNode&)      {}
void RazerGenerator::visit(ExprCallNode&)     {}
void RazerGenerator::visit(ExprBinopNode&)    {}
void RazerGenerator::visit(ExprUnopNode&)     {}
void RazerGenerator::visit(ExprTernaryNode&)  {}
void RazerGenerator::visit(ExprRandomRangeNode&) {}

// ── 元信息 ────────────────────────────────────────────────────────────────────

void RazerGenerator::visit(CommentNode& node)
{
    FlatEvent ev;
    ev.kind = FlatEvent::Kind::Comment;
    ev.text = node.text;
    pushEvent(ev);
}

void RazerGenerator::visit(RawNode& node)
{
    FlatEvent ev;
    ev.kind = FlatEvent::Kind::Comment;
    ev.text = "[RAW] " + node.code;
    pushEvent(ev);
}
