/*
 * AhkGenerator.cpp  —  AIR 树 → AHK v2 代码生成器实现
 */
#include "AhkGenerator.h"
#include "AhkKeyMap.h"
#include <sstream>
#include <algorithm>
using namespace AIR;

AhkGenerator::AhkGenerator(std::vector<AIRDiagnostic>& diags) : m_diags(diags) {}

// ── 输出辅助 ──────────────────────────────────────────────────────────────────
std::string AhkGenerator::ind() const { return std::string(m_depth * 4, ' '); }
void AhkGenerator::line(const std::string& s) { m_out << ind() << s << "\n"; }
void AhkGenerator::write(const std::string& s) { m_out << s; }
void AhkGenerator::nl() { m_out << "\n"; }

std::string AhkGenerator::expr(AIRNode& node) {
    AhkGenerator sub(m_diags); node.accept(sub); return sub.result();
}
std::string AhkGenerator::keyStr(AIRKey k, const std::string& raw) {
    if (k != AIRKey::KEY_UNKNOWN) { auto s = AhkKeyMap::AIRToAhk(k); if (!s.empty()) return s; }
    return raw.empty() ? "Unknown" : raw;
}
std::string AhkGenerator::modPfx(ModMask m) {
    std::string s;
    if (hasModifier(m, ModMask::Ctrl))  s += '^';
    if (hasModifier(m, ModMask::Alt))   s += '!';
    if (hasModifier(m, ModMask::Shift)) s += '+';
    if (hasModifier(m, ModMask::Win))   s += '#';
    return s;
}
std::string AhkGenerator::binOpStr(BinOp op) {
    switch (op) {
    case BinOp::Add: return "+";  case BinOp::Sub: return "-";
    case BinOp::Mul: return "*";  case BinOp::Div: return "/";
    case BinOp::OpMod: return " mod ";
    case BinOp::Pow: return "**";
    case BinOp::Eq:  return " = "; case BinOp::Neq: return " != ";
    case BinOp::Lt:  return " < "; case BinOp::Gt:  return " > ";
    case BinOp::Lte: return " <= ";case BinOp::Gte: return " >= ";
    case BinOp::OpAnd: return " && "; case BinOp::OpOr: return " || ";
    case BinOp::Concat: return " . ";
    default: return "?";
    }
}
void AhkGenerator::warn(const std::string& msg, int srcLine) {
    line("; [WARNING] " + msg);
    m_diags.push_back({ DiagLevel::Warning, srcLine, msg, "该节点已转为注释，请手动处理" });
}

// ── 程序结构 ──────────────────────────────────────────────────────────────────
void AhkGenerator::visit(ProgramNode& node) {
    line("; Generated by AhkPlugin v1.0.0");
    line("; AutoHotkey v2");
    nl();
    for (auto& c : node.children) {
        c->accept(*this);
        if (c->type != AIRNodeType::Comment) nl();
    }
}
void AhkGenerator::visit(SequenceNode& node) {
    for (auto& c : node.children) c->accept(*this);
}
void AhkGenerator::visit(FunctionDefNode& node) {
    std::string sig = node.name + "(";
    for (size_t i = 0;i < node.params.size();++i) { if (i) sig += ", "; sig += node.params[i]; }
    sig += ")";
    line(sig + " {"); push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop(); line("}");
}
void AhkGenerator::visit(FunctionCallNode& node) {
    std::string s = node.name + "(";
    for (size_t i = 0;i < node.children.size();++i) { if (i) s += ", "; s += expr(*node.children[i]); }
    line(s + ")");
}

// ── 触发器 / 热键 ─────────────────────────────────────────────────────────────
void AhkGenerator::visit(TriggerNode& node) {
    std::string hk;
    if (node.triggerEvent == TriggerEvent::MouseButtonDown || node.triggerEvent == TriggerEvent::KeyDown)
        hk = modPfx(node.modifiers) + keyStr(node.key);
    else { warn("TriggerNode(非按下事件)", node.srcLine); return; }
    write("~" + hk + "::\n{\n"); push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop(); write("}\n");
}
void AhkGenerator::visit(HotkeyNode& node) {
    std::string pfx = node.passthrough ? "~" : "";
    std::string hk = pfx + modPfx(node.modifiers) + keyStr(node.key);
    write(hk + "::\n{\n"); push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop(); write("}\n");
}

// ── 控制流 ────────────────────────────────────────────────────────────────────
void AhkGenerator::visit(IfNode& node) {
    if (node.children.size() < 2) { warn("IfNode 不完整", node.srcLine);return; }
    write(ind() + "if (" + expr(*node.children[0]) + ") {\n"); push();
    node.children[1]->accept(*this); pop();
    if (node.hasElse()) {
        line("} else {"); push(); node.children[2]->accept(*this); pop();
    }
    line("}");
}
void AhkGenerator::visit(LoopCountNode& node) {
    if (node.children.size() < 2) { warn("LoopCountNode 不完整");return; }
    write(ind() + "Loop " + expr(*node.children[0]) + " {\n"); push();
    node.children[1]->accept(*this); pop(); line("}");
}
void AhkGenerator::visit(LoopWhileNode& node) {
    if (node.children.size() < 2) { warn("LoopWhileNode 不完整");return; }
    write(ind() + "while (" + expr(*node.children[0]) + ") {\n"); push();
    node.children[1]->accept(*this); pop(); line("}");
}
void AhkGenerator::visit(LoopDoWhileNode& node) {
    // AHK v2 无 do-while，用 loop + if(cond) break 模拟 repeat...until
    if (node.children.size() < 2) { warn("LoopDoWhileNode 不完整");return; }
    line("; [do-while] repeat...until → loop + break");
    line("loop {"); push();
    node.children[0]->accept(*this);                         // 循环体
    write(ind() + "if (" + expr(*node.children[1]) + ")\n");       // until 条件
    push(); line("break"); pop();
    pop(); line("}");
}
void AhkGenerator::visit(LoopInfiniteNode& node) {
    line("loop {"); push();
    if (!node.children.empty()) node.children[0]->accept(*this);
    pop(); line("}");
}
void AhkGenerator::visit(BreakNode&) { line("break"); }
void AhkGenerator::visit(ContinueNode&) { line("continue"); }
void AhkGenerator::visit(ReturnNode& node) {
    if (node.hasValue()) { write(ind() + "return " + expr(*node.children[0]) + "\n"); }
    else line("return");
}
void AhkGenerator::visit(LabelNode& node) {
    int saved = m_depth; m_depth = 0; line(node.name + ":"); m_depth = saved;
}
void AhkGenerator::visit(GotoNode& node) { line("goto " + node.target); }

// ── 变量 ──────────────────────────────────────────────────────────────────────
void AhkGenerator::visit(VarAssignNode& node) {
    write(ind() + node.name + " := ");
    if (!node.children.empty()) write(expr(*node.children[0]));
    write("\n");
}
void AhkGenerator::visit(VarDeclareNode& node) {
    std::string kw;
    switch (node.scope) { case VarScope::Global:kw = "global "; break; case VarScope::Static:kw = "static "; break; default:kw = "local "; }
                                               if (node.hasInitValue()) { write(ind() + kw + node.name + " := " + expr(*node.children[0]) + "\n"); }
                                               else line(kw + node.name);
}

// ── 键盘动作 ──────────────────────────────────────────────────────────────────
void AhkGenerator::visit(KeyDownNode& node) { line("Send \"{" + keyStr(node.key, node.rawKey) + " down}\""); }
void AhkGenerator::visit(KeyUpNode& node) { line("Send \"{" + keyStr(node.key, node.rawKey) + " up}\""); }
void AhkGenerator::visit(KeyTapNode& node) {
    std::string k = keyStr(node.key, node.rawKey);
    bool bare = (k.size() == 1 && (std::isalpha((unsigned char)k[0]) || std::isdigit((unsigned char)k[0])));
    if (node.holdMs > 0) {
        line("Send \"{" + k + " down}\""); line("Sleep " + std::to_string(node.holdMs)); line("Send \"{" + k + " up}\""); return;
    }
    if (node.count == 1) { line(bare ? "Send \"" + k + "\"" : "Send \"{" + k + "}\""); }
    else line("Send \"{" + k + " " + std::to_string(node.count) + "}\"");
}
void AhkGenerator::visit(KeySendStringNode& node) {
    std::string esc; for (char c : node.text) { if (c == '"')esc += "`\"";else if (c == '`')esc += "``";else if (c == '\n')esc += "`n";else if (c == '\t')esc += "`t";else esc += c; }
    line("SendText \"" + esc + "\"");
}

// ── 鼠标动作 ──────────────────────────────────────────────────────────────────
void AhkGenerator::visit(MouseMoveNode& node) {
    if (node.children.size() < 2) { warn("MouseMoveNode 缺坐标");return; }
    std::string x = expr(*node.children[0]), y = expr(*node.children[1]);
    if (node.coordType == CoordType::CoordRelative) line("MouseMove " + x + ", " + y + ", 0, \"R\"");
    else line("MouseMove " + x + ", " + y);
}
void AhkGenerator::visit(MouseClickNode& node) {
    std::string btn = keyStr(node.key);
    if (node.children.size() >= 2) {
        std::string x = expr(*node.children[0]), y = expr(*node.children[1]);
        std::string cnt = node.count != 1 ? ", " + std::to_string(node.count) : "";
        line("MouseClick \"" + btn + "\", " + x + ", " + y + cnt);
    }
    else if (node.key == AIRKey::KEY_MOUSE_LEFT && node.count == 1) line("Click");
    else line("Click \"" + btn + "\"" + (node.count != 1 ? " " + std::to_string(node.count) : ""));
}
void AhkGenerator::visit(MouseDownNode& node) { line("Click \"" + keyStr(node.key) + " down\""); }
void AhkGenerator::visit(MouseUpNode& node) { line("Click \"" + keyStr(node.key) + " up\""); }
void AhkGenerator::visit(MouseScrollNode& node) {
    std::string d;
    switch (node.dir) {
    case ScrollDir::Up:d = "WheelUp";break;case ScrollDir::Down:d = "WheelDown";break;
    case ScrollDir::Left:d = "WheelLeft";break;default:d = "WheelRight";
    }
    std::string amt = (!node.children.empty()) ? " " + expr(*node.children[0]) : "";
    line("Click \"" + d + amt + "\"");
}

// ── 时间 ──────────────────────────────────────────────────────────────────────
void AhkGenerator::visit(SleepNode& node) {
    write(ind() + "Sleep ");
    if (!node.children.empty()) write(expr(*node.children[0])); else write("0");
    write("\n");
}

// ── 查询 ──────────────────────────────────────────────────────────────────────
void AhkGenerator::visit(QueryKeyStateNode& node) {
    // 出现在表达式上下文，不加换行
    write("GetKeyState(\"" + keyStr(node.key) + "\", \"P\")");
}

// ── 表达式 ────────────────────────────────────────────────────────────────────
void AhkGenerator::visit(ExprNumberNode& node) {
    if (node.value == (long long)node.value) write(std::to_string((long long)node.value));
    else write(std::to_string(node.value));
}
void AhkGenerator::visit(ExprStringNode& node) {
    std::string esc; for (char c : node.value) { if (c == '"')esc += "`\"";else if (c == '`')esc += "``";else if (c == '\n')esc += "`n";else esc += c; }
    write("\"" + esc + "\"");
}
void AhkGenerator::visit(ExprBoolNode& node) { write(node.value ? "true" : "false"); }
void AhkGenerator::visit(ExprVarNode& node) { write(node.name); }
void AhkGenerator::visit(ExprCallNode& node) {
    write(node.name + "(");
    for (size_t i = 0;i < node.children.size();++i) { if (i) write(", "); node.children[i]->accept(*this); }
    write(")");
}
void AhkGenerator::visit(ExprBinopNode& node) {
    if (node.children.size() < 2) return;
    write("("); node.children[0]->accept(*this);
    write(binOpStr(node.op));
    node.children[1]->accept(*this); write(")");
}
void AhkGenerator::visit(ExprUnopNode& node) {
    if (node.children.empty()) return;
    write(node.op == UnOp::OpNot ? "!" : "-");
    write("("); node.children[0]->accept(*this); write(")");
}
void AhkGenerator::visit(ExprTernaryNode& node) {
    if (node.children.size() < 3) return;
    write("("); node.children[0]->accept(*this); write(" ? ");
    node.children[1]->accept(*this); write(" : ");
    node.children[2]->accept(*this); write(")");
}
void AhkGenerator::visit(ExprRandomRangeNode& node) {
    if (node.children.size() < 2) { write("Random(0,100)");return; }
    write("Random("); node.children[0]->accept(*this);
    write(", "); node.children[1]->accept(*this); write(")");
}

// ── 元信息 ────────────────────────────────────────────────────────────────────
void AhkGenerator::visit(CommentNode& node) {
    if (node.isInline) write("  ; " + node.text);
    else line("; " + node.text);
}
void AhkGenerator::visit(RawNode& node) { line("; [RAW] " + node.code); }